### PR TITLE
Challenge added: subsetting data

### PR DESCRIPTION
**Pull request by mikblack**
Added challenge for accessing and operating on subsets of data object.
Answer options cover potential misconceptions about R syntax.  
Alternative would be to provide numeric answers for each (3, 2.5, 1.5, 2) and ask students to write R commands (involving x and the mean command) that would produce those outputs.

### CODE REVIEW

**Comment by jdblischak** [comment]
Thanks for the PR, @mikblack. We purposely avoid the class matrix in the novice lessons so that we can focus on how to write code to perform a data analysis without getting bogged down in discussions of data structures. The challenge above involves slicing a vector. Perhaps you could add a challenge that involves slicing the data frame with the inflammation data, `dat`? For example, "Select the inflammation data for patients 3 through 6 on days 9 through 17."

**Comment by gvwilson** [comment]
+1 to slicing the inflammation data frame - @mikblack can you please give it a throw?

**Comment by mikblack** [comment]
Done - added and made pull request.

**Comment by jdblischak** [comment]
Replaced by #49.

**Pull request closed without merging**
