### PR TITLE
Change variable names in temperature functions for consistency

### PR DESCRIPTION
**Pull request by colinnavin**
Please delete the text below before submitting your contribution. 

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate Hertweck (k8hertweck@gmail.com).  

---

### CODE REVIEW

**Comment by colinnavin** [comment]
Hi
First attempt at branching, pushing etc, hope it was all done correctly.
The idea was to make the variable names in the functions a bit more consistent.
cheers
Colin

**Comment by ErinBecker** [comment]
Looks good to me @colinnavin. Thanks!

**Comment by colinnavin** [comment]
Hi Erin

Thanks for the feedback.

I finished my checkout just the other day and it made me wonder how my suggestion went.

cheers

Colin


Colin Navin

PhD Candidate

Department of Physics and Astronomy

Building E6B, Level 2, Room 2.205

Macquarie University, NSW 2109

Australia

t: +61 (0)2 98508974

f: +61 (0)2 98508115

e: colin.navin@mq.edu.au<mailto:Email%3Acolin.navin@students.mq.edu.au>

[Macquarie University]<http://mq.edu.au/>

CRICOS Provider Number 00002J. Think before you print.
Please consider the environment before printing this email.

This message is intended for the addressee named and may
contain confidential information. If you are not the intended
recipient, please delete it and notify the sender. Views expressed
in this message are those of the individual sender, and are not
necessarily the views of Macquarie University.

________________________________

**Comment by katrinleinweber** [comment]
Hello @colinnavin! Sorry for the long delay here. Now that we are one maintainer more here, things should go faster again. I have a slight improvement suggestion to this PR, that I would like to get your feedback on (and @ErinBecker's, @hdashnow's and @chendaniely's as well):

How about using only `_C`, `_K` and `_F` in the variable names, but expanding `fahr_` to `fahrenheit_` in the function name? That would IMHO align nicely with both the names and abbreviations of the temperatur units/scales.

**Comment by ErinBecker** [comment]
@katrinleinweber - I like your suggestion, but would argue that the original PR that @colinnavin put in is itself a substantial improvement that could be merged on its own without changes. My suggestion would be to merge this PR and put in another PR to suggest the change you suggested above. 

Merging @colinnavin's PR as is will ensure that he gets authorship credit for this change (ie for the idea of improving the variable names).

**Pull request merged**
