### PR TITLE
Added DISCUSSION.md and note within to address issue #58

### PR DESCRIPTION
**Pull request by mlammens**
Created a DISCUSSION.md file for the R novice lessons. Within it I added notes to address issue #58

### CODE REVIEW

**Comment by chendaniely** [comment]
@mlammens I forgot what you were trying to do during the workshop, but
`rowSums` and `rowMeans` will do rowwise `sum` and `mean` on dataframe

**Comment by jdblischak** [comment]
Thanks for this, @mlammens. Here are some minor things to update:

*  Filename should be discussion.html
*  Change the header of the section to level 3 (i.e. `###`)
*  Mention that taking the mean/median of a row also needs to be avoided in lesson 01.
*  Mention that the recommended solution is to the problem is to not apply these functions to rows.
*  Remove the unnecessary spaces in the R code (see [here][adv-r] and [here][google]).

[adv-r]: http://adv-r.had.co.nz/Style.html
[google]: http://google-styleguide.googlecode.com/svn/trunk/Rguide.xml#spacing

**Comment by mlammens** [comment]
@jdblischak RE your first point, should I be pushing the *.md or *.html file? I thought the former.

**Comment by jdblischak** [comment]
Correct, you should push the md file. But you'll have to update the name of the html file in index.md as well.

**Comment by mlammens** [comment]
@jdblischak I made the suggested changes.

**Comment by jdblischak** [comment]
Thanks, @mlammens.

**Pull request merged**
