### PR TITLE
Moving motivation to instructors guide

### PR DESCRIPTION
**Pull request by gvwilson**
1.  Incorporate deletion of slideshow files from https://github.com/swcarpentry/lesson-template/pull/273
2.  Move content of `motivation.md` to `instructors.md`
3.  Pull in other recent changes to lesson template.

### CODE REVIEW

**Comment by jdblischak** [comment]
Sorry, I am a little confused by this PR, especially since it won't merge automatically. A few questions:

1. How does it relate to PR #128 that we already merged?
2. Why does it include so many commits that are already present in our repo?
3. Because that file includes the answers to challenges, we write it in R Markdown, i.e. [instructors.Rmd](https://github.com/swcarpentry/r-novice-inflammation/blob/gh-pages/instructors.Rmd). Is that what is causing so many problems?

**Comment by gvwilson** [comment]
Let me have another look at this one over the weekend - we're seeing 
similar problems with the novice Python lesson.

**Comment by gvwilson** [comment]
@jdblischak rebuilt this one - sorry for delay.

**Comment by jdblischak** [comment]
Waiting for #123 to be merged first.

**Pull request merged**
