### PR TITLE
Update 01-starting-with-data.html

### PR DESCRIPTION
**Pull request by raynamharris**
Added a statement indicating that we were leaving read.csv line of thought to illustrate a principle with numbers

### CODE REVIEW

**Comment by jdblischak** [comment]
Thanks for the PR, @raynamharris.

First, I apologize that the documentation for this repo is lacking. I am currently working on fixing that. When editing, you should directly change the source R Markdown file, not the html. To render the html, you'll need to run `make preview` from the base of the repository (see [here][] for the dependencies to install first).

Second, I don't think it is necessary to have a sub-heading just to introduce assigning a variable. If you think the transition is too quick, perhaps you could change the wording of the previous sentence or add an extra sentence or two without the header.

Also, I've recently added lots of [issues][] regarding transitioning the repo to conform to the new lesson template. Maybe one of those would also interest you.

[here]: https://github.com/swcarpentry/lesson-template#dependencies
[issues]: https://github.com/swcarpentry/r-novice-inflammation/issues

**Comment by raynamharris** [comment]
Thanks John,

Sorry, this is the very first pull request I ever made, and I wasn't sure
how I was supposed to do things.  Is there a good SWC or Git tutuorial on
that?

Thanks for the suggestions. I'll look into the issues next week (submitting
a grant tomorrow and still have lots to do on it!)

Rayna

On Wed, Jan 14, 2015 at 9:21 PM, John Blischak <notifications@github.com>
wrote:

> Thanks for the PR, @raynamharris <https://github.com/raynamharris>.
>
> First, I apologize that the documentation for this repo is lacking. I am
> currently working on fixing that. When editing, you should directly change
> the source R Markdown file, not the html. To render the html, you'll need
> to run make preview from the base of the repository (see here
> <https://github.com/swcarpentry/lesson-template#dependencies> for the
> dependencies to install first).
>
> Second, I don't think it is necessary to have a sub-heading just to
> introduce assigning a variable. If you think the transition is too quick,
> perhaps you could change the wording of the previous sentence or add an
> extra sentence or two without the header.
>
> Also, I've recently added lots of issues
> <https://github.com/swcarpentry/r-novice-inflammation/issues> regarding
> transitioning the repo to conform to the new lesson template. Maybe one of
> those would also interest you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swcarpentry/r-novice-inflammation/pull/9#issuecomment-70034410>
> .
>



-- 
Rayna M. Harris
Graduate Student, Hans Hofmann Lab
The University of Texas at Austin
http://cichlid.biosci.utexas.edu/

Training & Outreach
Center for Computational Biology & Bioinformatics
http://www.ccbb.utexas.edu/

**Comment by jdblischak** [comment]
No worries, @raynamharris. The SWC [version control lessons][git] have a lesson on [collaborating][collab] that would be helpful for you to read. The [Pro Git][pro] chapter on [Contributing to a Project][contrib] is also good. If branching is still foreign to you, you can make your changes on the main `gh-pages` and submit that as a PR since that is easier.

[git]: http://software-carpentry.org/v5/novice/git
[collab]: http://software-carpentry.org/v5/novice/git/02-collab.html
[pro]: http://git-scm.com/book/en/v2
[contrib]: http://git-scm.com/book/en/v2/GitHub-Contributing-to-a-Project

**Comment by jdblischak** [comment]
@raynamharris, good luck with the grant submission!

When you're ready, I'd recommend you tackle either issue #18 or #20. They will give you the chance to learn how to submit changes and also help us with the transition to the new lesson template. If you let me know which one you would like to try, please let me know and I will assign the issue to you so that no one else fixes it in the meantime.

**Comment by jdblischak** [comment]
I've add some guidelines on [how to contribute][contributing] to this repo to the README. Please let me know if you have any questions.

[contributing]: https://github.com/swcarpentry/r-novice-inflammation#contributing

**Comment by gvwilson** [comment]
Hi all,
Is this one ready to merge, has it gone stale, or...?
Thanks,
Greg

**Comment by jdblischak** [comment]
Let's close it. @raynamharris, please feel free to update and repoen this PR or to submit a new PR. If you have questions on how best to contribute, please feel free to ask on the [r-discuss][] mailing list.

[r-discuss]: http://lists.software-carpentry.org/mailman/listinfo/r-discuss_lists.software-carpentry.org

**Pull request closed without merging**
