### PR TITLE
Update 01-supp-intro-rstudio.Rmd

### PR DESCRIPTION
**Pull request by willpitchers**
I added a tip callout about tab-completion to the RStudio introduction.

### CODE REVIEW

**Comment by jdblischak** [comment]
Thanks for the PR, @willpitchers.

I like the content, but what about moving it out of the callout box? Unlike the other lessons, this entire lesson is little tidbits. Callout boxes are for when you don't want to disrupt the main narrative. I don't think tab-completion needs to be treated differently than switching between windows or sending code from a script to the console. What do you think?

**Comment by willpitchers** [comment]
Hey John – that's a good point. I'm fine with moving it out of the callout
box.

W

**Comment by jdblischak** [comment]
OK. Great. Please respond to the thread once you make the change to remind me to merge.

**Comment by willpitchers** [comment]
I've made the edit in my forked version – I guess that it'll appear as a separate PR now?
Cheers,  W

**Comment by jdblischak** [comment]
I'm not quite sure what happened because this PR says it is from an "unknown repository". Normally you could just update the branch in your fork and the PR would be automatically updated.

In this case, you'll need to create a new PR from your branch `willpitchers-patch-1`.

**Pull request closed without merging**
