### PR TITLE
Update maintainer list

### PR DESCRIPTION
**Pull request by katrinleinweber**
Hi @diyadas!

As discussed via e-mail I'll step down by the end of October. Before that, I plan to

- [x] get #421 ready for review
- [x] add @HaoZeke

The [last (almost) 2 years](https://github.com/swcarpentry/r-novice-inflammation/commit/0b03d2c7a1c517b07d1c16b04577bac944c715ff) were are good learning experience in R & Git for me, thanks also to the many Carpentries people with whom I've worked together on our various lessons :-)

PS: On this occasion @chendaniely: If you're still on-board, please let us know.

### CODE REVIEW

**Comment by katrinleinweber** [comment]
I cancelled Travis, because it's only a Markdown change.

**Comment by diyadas** [comment]
Thank you @katrinleinweber!

I’ve learned a lot from you and I wish you well on your next venture!

**Comment by chendaniely** [comment]
I think I have to be placed on the alumni list :x
I'm currently working on a project for my PhD that may fold back into Data Carpentry, so I'll give the mailing list a ping when things are a bit more settled on my end.

It's sad I have to let things go, but it's for the best (for everyone involved)

**Comment by HaoZeke** [comment]
Hi everyone, sorry for dragging my feet on this. I hope it wasn't remiss of me to format the file with `prettier` as well. Thank you @chendaniely and @katrinleinweber for all your hard work and I hope to be as productive as everyone else. Very glad to be moving forward with @diyadas on this.

**Comment by HaoZeke** [comment]
Shall I merge this? @diyadas

**Pull request merged**
