### PR TITLE
Compress data/ folder to make new zip file to address Issue #162

### PR DESCRIPTION
**Pull request by pschloss**

### CODE REVIEW

**Comment by chendaniely** [comment]
#162 mentions `car-speeds.csv`.
Is this included in the zip file? Or am I doing something wrong..?

**Comment by pschloss** [comment]
Sorry for the confusion and not stating what I actually did! At the [beginning of the tutorial](http://swcarpentry.github.io/r-novice-inflammation/) the learners download a zip file that has numerous files in it. #162 resulted because not all of the files were included in that zip file. This PR recreate the zip file to include `car-speeds.csv` and several other files. This was a compression of the `data` directory in the repository. In the future it might be good to have a way to automate the creation of the zip file whenever the `data` directory is updated.

**Comment by chendaniely** [comment]
@pschloss I'll take a look again, I didn't see the `car-speeds.csv` when I was performing git-mastics in the wee hours of the night.

**Comment by pschloss** [comment]
Doh! Sorry, I'm not sure what happened, but the newer commit should have the missing files.

**Comment by chendaniely** [comment]
just confirming: I see:

```
$ ls -l
total 124
-rw-r--r-- 1 dchen users 2022 Jun 15 12:29 car-speeds-cleaned.csv
-rw-r--r-- 1 dchen users 1614 Jun 15 12:29 car-speeds.csv
-rw-r--r-- 1 dchen users 5365 Jun 15 12:29 inflammation-01.csv
-rw-r--r-- 1 dchen users 5314 Jun 15 12:29 inflammation-02.csv
-rw-r--r-- 1 dchen users 5343 Jun 15 12:29 inflammation-03.csv
-rw-r--r-- 1 dchen users 5367 Jun 15 12:29 inflammation-04.csv
-rw-r--r-- 1 dchen users 5345 Jun 15 12:29 inflammation-05.csv
-rw-r--r-- 1 dchen users 5330 Jun 15 12:29 inflammation-06.csv
-rw-r--r-- 1 dchen users 5342 Jun 15 12:29 inflammation-07.csv
-rw-r--r-- 1 dchen users 5352 Jun 15 12:29 inflammation-08.csv
-rw-r--r-- 1 dchen users 5327 Jun 15 12:29 inflammation-09.csv
-rw-r--r-- 1 dchen users 5342 Jun 15 12:29 inflammation-10.csv
-rw-r--r-- 1 dchen users 5363 Jun 15 12:29 inflammation-11.csv
-rw-r--r-- 1 dchen users 5340 Jun 15 12:29 inflammation-12.csv
-rw-r--r-- 1 dchen users 5065 Jun 15 12:29 sample.csv
-rw-r--r-- 1 dchen users   12 Jun 15 12:29 small-01.csv
-rw-r--r-- 1 dchen users   15 Jun 15 12:29 small-02.csv
-rw-r--r-- 1 dchen users   12 Jun 15 12:29 small-03.csv

```

**Comment by pschloss** [comment]
Great - the `car-speeds.csv` is the specific one that the issue was missing

**Comment by chendaniely** [comment]
@pschloss thanks!

**Pull request merged**
