### PR TITLE
added introduction text+ inflammation data downlaod

### PR DESCRIPTION
**Pull request by areejalsheikh**
I figured at workshops when students only take R, they need a separate intro even if it's a replicate of the one at Python. More importantly, having a dedicated link to R-inflammation data.

P.S: current link to the R-inflammation data is broken. Could you please fix that?

### CODE REVIEW

**Comment by dhaine** [comment]
Thanks for the PR @areejalsheikh ! This would make our r-novice-inflammation index in line with the one for python. Could you just change R-novice-inflammation to r-novice-inflammation? I know it's capital R but we use small r everywhere to name this lesson...
There is no zipped file for the data sets and I'll add that. Note that we have a few extra datasets than the python lesson, so it's better removing your note on ignoring this step.

**Comment by areejalsheikh** [comment]
Done but I'm not sure if you can see it. Do I need a pull request for that too?

**Comment by dhaine** [comment]
No need for a PR, the changes are there. Just one small change though. Could you change R-novice-inflammation-data.zip to r-novice-inflammation-data.zip? Then I'll be able to accept your changes. Thanks!

**Comment by jdblischak** [comment]
Thanks for the PR, @areejalsheikh. It was recently incorporated in #152.

**Pull request merged**
