### PR TITLE
Update style to v9.4.0

### PR DESCRIPTION
**Pull request by rgaiacs**
A few changes on style.
Need manual changes at CONTRIBUTING.md!

### CODE REVIEW

**Comment by katrinleinweber** [comment]
>  Need manual changes at CONTRIBUTING.md!

Do you mean: updating it from the part between https://github.com/swcarpentry/r-novice-inflammation/pull/350/files#diff-64407706ac5c5287e1041a5f89fd8bc1R18 and https://github.com/swcarpentry/r-novice-inflammation/pull/350/files#diff-64407706ac5c5287e1041a5f89fd8bc1R167?

**Comment by rgaiacs** [comment]
@katrinleinweber I remember https://github.com/swcarpentry/lesson-example/pull/186/files#diff-6a3371457528722a734f3c51d9238c13L72 but I don't know if it applies to this repo.

**Comment by katrinleinweber** [comment]
@diyadas Do you want to try it as well, before we merge?

**Comment by diyadas** [comment]
Looks good, thanks @rgaiacs and @katrinleinweber !

**Pull request merged**
