### PR TITLE
Update chunk hooks for pandoc syntax highlighting

### PR DESCRIPTION
**Pull request by jdblischak**
With the switch from jekyll to pandoc for building lessons, we needed to update the chunk hooks that control how knitr surrounds input and output code blocks.

### CODE REVIEW

**Comment by jdblischak** [comment]
Also, @gvwilson, tools/chunk-options.R can now be merged into the main lesson-template repo for proper rendering of R Markdown source files.

**Comment by gvwilson** [comment]
Thanks John - does that mean the Makefile in r-novice-inflammation is 
good as well?

**Comment by jdblischak** [comment]
Yes, the Makefile also works. I ran it to generate all the rendered files in this PR.

**Comment by jdblischak** [comment]
@gvwilson, could you please merge this PR or give me the +1 to merge? This affects all the rendered files, so it will be much easier to merge the contributions of the recent round of trainees if these changes land before they start editing.

**Pull request merged**
