### PR TITLE
Reformat challenges (#19)

### PR DESCRIPTION
**Pull request by dhaine**

### CODE REVIEW

**Comment by jdblischak** [comment]
Thanks, @dhaine. This looks good. The only bad thing is that when the challenge includes knitr chunks, the remainder is formatted as a typical block quote and not as a challenge. I'm not sure if there is a way to improve this.

**Comment by jdblischak** [comment]
Fixes #19.

**Comment by dhaine** [comment]
I couldn't find a way to solve the post-chunk formatting issue. For now we can leave it like that until someone come with a better solution.

**Comment by jdblischak** [comment]
Agreed.

**Pull request merged**
