### PR TITLE
Renaming challenges

### PR DESCRIPTION
**Pull request by tomwright01**
Named challenges in all lessons. Addresses issue #33

### CODE REVIEW

**Comment by jdblischak** [comment]
Thanks, @tomwright01. This is really useful.

The only issue I have with this PR is that you sumbitted lots of changes in the last commit. For example, all the figures are still basically identical. Also, we don't currently have the pdf files included in the repo. If we decide that is something we want to do, I'd like to get public comment on it in a separate PR.

The easiest way to resolve this is for you to just remove the last commit from this PR. I'll handle rendering the html after it is merged. This should be as easy as the following:

```
git checkout renaming_challenges
git reset --hard 43701c250f2d16ce904467b5081c9c3a863a5458
git push -f origin renaming_challenges
```

**Comment by tomwright01** [comment]
Done, Sorry I misremembered the instructions for rendering the html. The
last commit was just the result of make preview on my system.
I have followed your suggestion and rolled back that commit.

**Comment by jdblischak** [comment]
No worries, @tomwright01. It is confusing. Before I was having everyone render the html for the PR, but that was causing lots of headaches due to merge conflicts.

**Comment by tomwright01** [comment]
Since I have a little time on my hands (home sick) I was just updating
README.md to clarify what should be committed. Shall I update .gitignore to
include *.html, *.md, *.pdf etc.?

**Comment by jdblischak** [comment]
No. While PRs should not include the rendered markdown or html, those still need to be added to the repo. I just do it myself after the PR lands, e.g. commit f5356b7b1b67f52f7c2cdcc236c0c5f5f5cf6f43.

Do you know about the recent addition of [CONTRIBUTING.md][]? The Contributing section of the README needs to point readers to that file, and then add specifics for this repo. Namely, 1) edits should be done to R Markdown files, and 2) point them towards the Issues of this repo. I was going to do this, but if you are eager go ahead.

[CONTRIBUTING.md]: https://github.com/swcarpentry/r-novice-inflammation/blob/gh-pages/CONTRIBUTING.md

**Pull request merged**
