### PR TITLE
Remove link to sequence in string definition in the glossary

### PR DESCRIPTION
**Pull request by cmd-ntrf**
Sequence is not part of the Glossary for R, only Python.

### CODE REVIEW

**Comment by chendaniely** [comment]
@hdashnow should we add sequence to the R reference?

the Python one is as follows:
```
sequence
A collection of information that is presented in a specific order. For example, in Python, a string is a sequence of characters, while a list is a sequence of any variable.
```

**Comment by hdashnow** [comment]
@chendaniely Yes, I think that's a good idea. The Python definition fits nicely, except maybe as an example we could use a vector instead of list.

**Comment by cmd-ntrf** [comment]
If the term is added to the glossary, it might requires some clarifications. I think in R, this more emphasis on the fact that a sequence has a specific order. Also `sequence` is a function in R, and `seq` is by definition returning a sequence. I am not sure if there is any other function in R that by definition returns a sequence else than `seq`.

**Comment by hdashnow** [comment]
What would you recommend, @cmd-ntrf? Delete or write a new definition?

**Comment by cmd-ntrf** [comment]
I would recommend deleting the link.

The term _sequence_ is used three times in the lesson. Each time it is used to explain the usage of the colon `:` with numbers. The term is sufficiently explained by the context and adding a definition could cause some confusion.

**Comment by hdashnow** [comment]
Sounds good. @chendaniely any objections?

**Comment by chendaniely** [comment]
Sounds great.  I'm convinced!

**Pull request merged**
