### PR TITLE
Pull Request for R Lessons, Lesson 01-starting-with-data.Rmd  from Noush...

### PR DESCRIPTION
**Pull request by noushing**
Dear Software Carpentry R team, 

In this few lines, I am trying to add another useful feature of R. using the “()” around a statement will print its assigned value automatically.

Best,
Noushin

### CODE REVIEW

**Comment by jdblischak** [comment]
Hi, Noushin. Thanks for the PR. I apologize it took so long for me to respond; I recently taught a workshop which took up most of my SWC time.

Could you please provide some use cases for why this is essential for novices to learn? I rarely ever use this trick, and the only time I do is when I am writing teaching materials with knitr (since it saves me from having to retype the name of the variable). Also, I am concerned it will be confusing to novices since all the various syntax marks (`[`, `(`, and `{`) are so arbitrary. We want them to remember that parentheses are used for function calls.

Also, there is the concern about the length of the teaching materials. This lesson already contains more content than most instructors are able to cover in a typical workshop. See this [post][] on the discuss mailing list for a recent converstation about this issue.

[post]: http://lists.software-carpentry.org/pipermail/discuss_lists.software-carpentry.org/2015-March/002853.html

**Comment by dhaine** [comment]
Agree with @jdblischak. Maybe it would be better as a Tip in 01-starting-with-data lesson?

**Comment by noushing** [comment]
Hello John and Denis,

I've used this quick printing trick in programs and had been helpful, and
thought that mentioning it can have advantages for new learners as well.
However, I totally agree that learning about too many new things in the
introductions can distract students. Including it within the Tip, as Denis
suggested, is a good idea.

Thank you,
Noushin

**Comment by jdblischak** [comment]
@noushing, do you intend to update the PR, including this as a Tip?

**Comment by noushing** [comment]
Sure, I can add it as a Tip, and make another Pull Request for your
approval.

**Comment by jdblischak** [comment]
You don't need to make a new PR. You can just update the current one. Any changes you make to your gh-pages branch will automatically be sent to this PR.

**Comment by noushing** [comment]
Thanks.

**Comment by jdblischak** [comment]
Thanks, @noushing.

**Pull request merged**
