### PR TITLE
generate md and html for PRs #167 #184 #172 #171 #173 #174

### PR DESCRIPTION
**Pull request by hdashnow**
@chendaniely could you please take a look at this? I'm seeing systematic differences in the html. I wonder if we have different versions of something?

### CODE REVIEW

**Comment by chendaniely** [comment]
It'll take a while, looking at 54 diffs isn't the easiest thing to do.
I've been rendering the `md` and `html` files as a `Rmd` PR is merged.

Also, I don't think you need to have any of the images or pdfs?
A lot of the png plots didn't really change.

**Comment by hdashnow** [comment]
@chendaniely No, don't look at all 54 diff! I just wanted to show you that there is consistent differences in the html, that don't seem to be related to changes in content e.g.:

```
-<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">setwd</span>(<span class="st">&quot;~/Desktop/r-novice-inflammation/&quot;</span>)</code></pre></div>
+<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">setwd</span>(<span class="st">&quot;~/Desktop/r-novice-inflammation/&quot;</span>)</code></pre>
  <p>
```

**Comment by hdashnow** [comment]
@jdblischak have you come across this before? Any suggestions?

**Comment by chendaniely** [comment]
Can we take the `png` and `pdf` images out of this PR?

**Pull request closed without merging**
