### PR TITLE
added sapply(df, class)

### PR DESCRIPTION
**Pull request by kdirek**
This is submitted as part of instructor training.

### CODE REVIEW

**Comment by chendaniely** [comment]
Hi @kdirek thanks for the PR!

while I agree that this is a useful dataframe function (I do this all the time),
it might be more complicated of a command when compared to the other commands listed.
I feel like this can be a comment or tip when we talk about `apply` or something similar.

@hdashnow, thoughts?

**Comment by chendaniely** [comment]
Also just realized that dataframe columns are stored as a `list`, so we'd also need to distinguish between `lapply` and `sapply`

**Comment by kdirek** [comment]
@chendaniely, I had the same thought on where to place this. For me the decision to include it here and not within the [loops/apply lesson](https://github.com/swcarpentry/r-novice-inflammation/blob/2017.02/_episodes_rmd/15-supp-loops-in-depth.Rmd) was because I felt it more closely aligns to the learning objectives for this lesson and we have already introduced `apply` in the  [first lesson](https://github.com/swcarpentry/r-novice-inflammation/blob/2017.02/_episodes_rmd/01-starting-with-data.Rmd). The information from `sapply(df,` `class)` can also be obtained using `str()` but I would argue the output is more accessible and as a result, more likely to feed into their working practice as it does for you and I.

As for `lapply`and `sapply`, that distinction is briefly outlined in the [loops/apply lesson](https://github.com/swcarpentry/r-novice-inflammation/blob/2017.02/_episodes_rmd/15-supp-loops-in-depth.Rmd) but we could definitely flesh it out a bit with examples.

**Comment by chendaniely** [comment]
@kdirek I've thought about where to place this.
I  I agree with you here putting it in this lesson.

I realized I actually try to show this as soon as possible when I'm teaching because it's such a useful snippet to code.

**Pull request merged**
