### PR TITLE
typo in setwd

### PR DESCRIPTION
**Pull request by TomKellyGenetics**
Hopefully makes start of lessons run smoothly
Spotted at Research Bazaar Dunedin 2016

### CODE REVIEW

**Comment by ppgardne** [comment]
Dammit Tom! I was hoping to fix this one. ;-P

**Comment by smcclatchy** [comment]
Add matching double quote to 
setwd("~/Desktop/r-novice-inflammation/")
in 01-starting-with-data.Rmd
under Loading Data.

**Comment by smcclatchy** [comment]
Merge with PRs #183 and #184.

**Comment by hdashnow** [comment]
Thanks! Fixed by merging #184

**Pull request closed without merging**
