### PR TITLE
Add template language for issues and PRs about lesson contribution an…

### PR DESCRIPTION
**Pull request by ErinBecker**
…d maintenance process

### CODE REVIEW

**Comment by ErinBecker** [comment]
I realized after submitting this PR yesterday that I didn't do a good job of documenting the rationale behind this or what it's trying to accomplish. My apologies.

I've been getting a significant number of questions from new instructors and instructor trainees about the lesson contribution process. Specifically, many trainees are worried that if their contributions aren't accepted they won't be able to qualify as instructors. Some are also worried or frustrated about not hearing back about their contributions for a while. I wanted to help communicate to contributors that the maintainers are volunteers who have many other time commitments and sometimes delay in reviewing PRs is inevitable, also that even if a specific contribution isn't incorporated, their input is still appreciated and welcome.

I'm hopeful that this language will help clarify the process and assuage some of these concerns, especially for new members of our community.

**Comment by chendaniely** [comment]
Thanks, @ErinBecker! Yeah, I totally fell off the track from November to about March.
I'm totally guilty of being the cause of this. :flushed:

**Comment by ErinBecker** [comment]
@chendaniely Thanks for merging!

**Comment by ErinBecker** [comment]
Added PR to styles https://github.com/swcarpentry/styles/pull/143

**Pull request merged**
