### PR TITLE
 Change: As part of Instructor certification, please see Part 1: smal…

### PR DESCRIPTION
**Pull request by SinghSat2010**
Change: As part of Instructor certification, please see Part 1: small contribution to the track "01-starting with data". I have improved the variable assignment operation example by enumerating three ways a variable can be assigned in R - 
1. Leftward (<-)
2. Rightward (->)
3. Equal (=)
 Additional I have illustrated with examples how the assignment operations are performed. 

My info : Satwinder Singh from Columbia University, email: ss4878@columbia.edu, git account: singhsat2010

### CODE REVIEW

**Comment by katrinleinweber** [comment]
Hello & welcome to the Carpentries as an instructor, @SinghSat2010 :-)

Regarding this particular suggestion, however, I have to say no to its current state, I'm sorry. The reasons are:

1. While `->` IMHO has its place in the end of a `%>%` pipeline, `=` is recommended against in both [Google's](https://google.github.io/styleguide/Rguide.xml#assignment) and the [tidyverse](http://style.tidyverse.org/syntax.html#assignment) style guides.

1. Adding another concept (like different assignments) [should be accompanied](https://github.com/swcarpentry/r-novice-inflammation/blob/master/CONTRIBUTING.md#what-not-to-contribute) by removing a less important concept. Please feel free to add more commits or to discuss what should be removed to make room for your suggestion.

Nonetheless: kind regards,
Katrin

**Comment by SinghSat2010** [comment]
Hi Katrin,

Thanks for the quick reply and interesting to note how the languages has
changed and evolved. With c/c++/java the equal assignment is ubiquitous
while there were references to leftward assignments. Sure I will look
through exercises and contrib more

Does this means I can move to step 2 of instructor training?


Regards
Satwinder

**Comment by diyadas** [comment]
Hello!

We as lesson maintainers do not manage the instructor certification process. As per the instructions, your PR does not need to be accepted to proceed to the next step, but you do need to let the people in charge of tracking your progress know that you did interact with us. Please see the instructions on this page for what to do: https://carpentries.github.io/instructor-training/checkout/

If you have questions about instructor certification, you can contact checkout@carpentries.org (the last link on that page).

Best of luck!
Diya

**Comment by ErinBecker** [comment]
A hearty thank you to the Maintainers @diyadas and @katrinleinweber for their speedy and polite responses! This is exactly what I like to see. Thank you @SinghSat2010 for your contribution, even though it was not incorporated into the lesson, it provokes valuable discussion and thought about the guiding principles behind the lesson. Please do move ahead to the next stage of instructor training checkout! We are looking forward to having you as part of our Instructor community.

**Pull request closed without merging**
