### PR TITLE
Additional challenge about the apply function

### PR DESCRIPTION
**Pull request by pennekampster**
NB: this exercise is submitted as part of the instructor checkout procedure. 

The idea behind the challenge is to test understanding of the apply function in the context of data.frames and subsets of data.frames. Four function calls involving the apply function are provided and their expected result has to be assigned. Both MARGIN arguments and the input data.frames are varied and the learner needs to anticipate how the results change as a function of aggregation along rows and columns, with the complication that the input varies.

### CODE REVIEW

**Comment by gvwilson** [comment]
Looks good to me - @hdashnow or @chendaniely ?

**Comment by chendaniely** [comment]
@pennekampster this is a good challenge question that can get students practicing the various ways data can be `apply`ed.
can you resubmit the question such that it doesn't use a multiple choice format.
This way it's consistent with the other challenge questions in the lesson.

**Comment by pennekampster** [comment]
@chendaniely Thanks for your comment, I will revise my challenge and send a new pull request.

**Comment by hdashnow** [comment]
Hey @pennekampster, are you still happy to make changes to this PR? We're trying to finalise this version of the notes ASAP.

**Comment by pennekampster** [comment]
Hey @hdashnow sorry for being slow on this one. I have adapted the challenge and hope you like it to be included for the new version.

**Comment by hdashnow** [comment]
Thanks @pennekampster!
Any chance you could throw in the solutions as well? Or you could just comment them here, and I'll add them in when add your challenge :)

**Comment by pennekampster** [comment]
Sure @hdashnow, added my solutions at the end of the challenge :)

**Comment by hdashnow** [comment]
Brilliant, thanks @pennekampster. I think this is a great challenge! 
I've rebased it and submitted it as a new PR here: #215

I'm closing this PR, but all your changes are in #215 😄 

Thanks for contributing!

**Comment by pennekampster** [comment]
Perfect, thanks for helping me through the challenge submission @hdashnow. It is my first but hopefully not the last time ;)

**Pull request closed without merging**
