### PR TITLE
fixes issue #217

### PR DESCRIPTION
**Pull request by butterflyskip**
A couple of questions:

 1) Should I include _episodes_rmd/.Rhistory to the PR? (included it for now)
 2) What are considered "old figures" referred to above? I have not done that part in this PR

### CODE REVIEW

**Comment by rgaiacs** [comment]
> Should I include _episodes_rmd/.Rhistory to the PR? (included it for now)

No.

**Comment by butterflyskip** [comment]
Okay.  Which brings up a question --- create another PR?  Or do a git revert?

**Comment by rgaiacs** [comment]
> Okay. Which brings up a question --- create another PR? Or do a git revert?

Hi @butterflyskip, different projects will have different suggestions of how to handle this. My preference would be to run

~~~
$ rm _episodes_rmd/.Rhistory
$ git commit -a --amend
$ git push -f origin issue217
~~~

This will create a new commit without the file, change the branch to that commit and push it to GitHub.

**Comment by butterflyskip** [comment]
Ugh!  sorry more questions from this newbie :-1: 

Does this mean I start the whole process again and then run all the commands you wrote above?

Apologies again ... seems like the fix would have been easier for someone more competent in git :-(

**Comment by butterflyskip** [comment]
Hi @rgaiacs, deleted the .Rhistory.

Thank you for the code.  Learned something new :+1:

**Comment by katrinleinweber** [comment]
Hi @rgaiacs! Can this be merged from your PoV? I get what the changes do, but feel that I don't know the full history.

**Comment by katrinleinweber** [comment]
Dear @butterflyskip, is this ready to merge from your PoV?

**Pull request merged**
