### PR TITLE
Change Tips to callout boxes

### PR DESCRIPTION
**Pull request by ateucher**
This is a start on #20; reformatting the Tips as callout boxes.  You don't need to merge this yet, as I'll add more commits to it, but I thought I would push up changes to the first files to get the PR started.  

The figures were re-rendered when ran `make preview`, but are identical. Let me know if you don't want me to commit them.

### CODE REVIEW

**Comment by jdblischak** [comment]
Thanks, @ateucher. I'll assign the issue to you.

No need to commit files that are modified, but not really changed. However, when there are new files you should commit those. For example, the newest version of knitr now adds a dash before the number when there are multiple plots generated by the same chunk, i.e. it used to be `chunk-plot2.png` but now it is `chunk-plot-2.png`.

**Comment by jdblischak** [comment]
Well nevermind, I can't actually assign the issue to you. But since you referenced this Issue in this thread it should be fine.

**Comment by gvwilson** [comment]
I've invited @ateucher to join the @swcarpentry team.

**Comment by ateucher** [comment]
Thanks @gvwilson! I've assigned myself now.

**Comment by ateucher** [comment]
@jdblischak I think this PR is ready for review and merge if it's acceptable.

**Comment by jdblischak** [comment]
Looks good. Thanks, @ateucher.

**Pull request merged**
