### PR TITLE
My contribution to lesson 1

### PR DESCRIPTION
**Pull request by jgalgarra**
- Extended explanation on where the data file is and why the subdirectory "data/" name must be included in the read.csv() call.
- Modified explanation of the usefulness of data frames.

### CODE REVIEW

**Comment by jdblischak** [comment]
Thanks for the PR, @jgalgarra. Overall I like the changes and want to have them merged.

There is one thing I would prefer that you change. You changed the use of the word "data" from singular to plural. While I understand that data was once used as a plural, it is now common to use it as a singular noun ([source](http://www.theguardian.com/news/datablog/2010/jul/16/data-plural-singular)).

Throughout the SWC lessons, the word "data" is used as a collective noun. If this is something you want to try and change, we would need to update all the lessons to be consistent. I recommend emailing the [discuss][] mailing list.

[discuss]: http://lists.software-carpentry.org/mailman/listinfo/discuss_lists.software-carpentry.org

Examples of data as collective noun:

*  [shell-novice lesson 6](https://github.com/swcarpentry/shell-novice/blob/bdfebab818e495e7c0d4886600bb354ed8aa6763/06-find.html#L224)
*  [python-novice-inflammation instructors guide](https://github.com/swcarpentry/python-novice-inflammation/blob/ac57fd9d265f834471a4cf8f2eb873bbb449c7b5/instructors.html#L33)
*  [python-novice-inflammation lesson 3](https://github.com/swcarpentry/python-novice-inflammation/blob/c97d5439210e0b0fc0b747ef276f9374facf7de9/03-lists.html#L64)
*  [sql-novice-survey lesson 8](https://github.com/swcarpentry/sql-novice-survey/blob/287a0091930f7a9f2a77278d63e489f60ac9d3d1/08-hygiene.html#L112)

**Comment by jgalgarra** [comment]
I close this PR and add the suggested change to the PR #82

**Comment by jgalgarra** [comment]
I close this PR and add the suggested change to the PR #82

**Comment by jgalgarra** [comment]
I close this PR and open PR105 to merge these changes with thos described in PR 82

**Pull request closed without merging**
